/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.AccountDirectory;

/**
 *
 * @author josephchakola
 */
public class AccountManagmentPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountManagePanel
     */
    private JPanel UserProcessContainer;
    private AccountDirectory directory;
    public AccountManagmentPanel(JPanel UserProcessContainer, AccountDirectory directory ) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.directory = directory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAccountCreate = new javax.swing.JButton();
        btnAccountManagement = new javax.swing.JButton();

        btnAccountCreate.setText("Create Account");
        btnAccountCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountCreateActionPerformed(evt);
            }
        });

        btnAccountManagement.setText("Manage Account");
        btnAccountManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountManagementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAccountManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAccountCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(335, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnAccountCreate)
                .addGap(18, 18, 18)
                .addComponent(btnAccountManagement)
                .addContainerGap(419, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccountCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountCreateActionPerformed
        // TODO add your handling code here:
        CreateAccountPanel ct = new CreateAccountPanel(UserProcessContainer,directory);
        UserProcessContainer.add("CreateAccountPanel",ct);
        CardLayout cl = (CardLayout) UserProcessContainer.getLayout();
        cl.next(UserProcessContainer);
    }//GEN-LAST:event_btnAccountCreateActionPerformed

    private void btnAccountManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountManagementActionPerformed
        // TODO add your handling code here:
        ManageAccountPanel panel = new ManageAccountPanel(UserProcessContainer,directory);
        UserProcessContainer.add("ManageAccountPanel",panel);
        CardLayout cl = (CardLayout) UserProcessContainer.getLayout();
        cl.next(UserProcessContainer);
    }//GEN-LAST:event_btnAccountManagementActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccountCreate;
    private javax.swing.JButton btnAccountManagement;
    // End of variables declaration//GEN-END:variables
}
